name: Run Selenium Tests

on:
  workflow_dispatch:
    inputs:
      browser:
        description: 'Select the Browser'
        required: true
        default: 'chrome'
        type: choice
        options:
          - chrome
          - firefox
  repository_dispatch:
    types:
      - run-selenium-tests

jobs:
  run-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Install Docker Compose
        run: |
          sudo curl -L "https://github.com/docker/compose/releases/latest/download/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
          sudo chmod +x /usr/local/bin/docker-compose
          docker-compose --version

      - name: Start Selenium Grid
        run: |
          docker-compose -f grid.yaml up --scale ${{ github.event.inputs.browser || github.event.client_payload.browser }}=2 -d

      - name: Wait for Grid
        run: |
          count=0
          while [ "$(curl -s http://localhost:4444/status | jq -r .value.ready)" != "true" ]; do
            count=$((count+1))
            echo "Attempt: $count"
            if [ "$count" -ge 30 ]; then
              echo "Hub not ready within 30 seconds"
              exit 1
            fi
            sleep 1
          done
          echo "Selenium Grid is up!"

      - name: Run Tests
        run: |
          docker-compose -f test-suites.yaml up --pull=always

      - name: Archive Test Results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: test-results
          path: |
            output/vendor-portal/emailable-report.html
            output/flight-reservation/emailable-report.html

      - name: Stop Containers
        if: always()
        run: |
          docker-compose -f grid.yaml down
          docker-compose -f test-suites.yaml down